/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class priv_xay_ticketSystem_test_JniTest_Human */

#ifndef _Included_priv_xay_ticketSystem_test_JniTest_Human
#define _Included_priv_xay_ticketSystem_test_JniTest_Human
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
