/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class priv_xay_ticketSystem_test_JniTest */

#ifndef _Included_priv_xay_ticketSystem_test_JniTest
#define _Included_priv_xay_ticketSystem_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     priv_xay_ticketSystem_test_JniTest
 * Method:    objectTest
 * Signature: ()[Lpriv/xay/ticketSystem/test/Human;
 */
JNIEXPORT jobjectArray JNICALL Java_priv_xay_ticketSystem_test_JniTest_objectTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
